import { executeProject } from '../engine/executor';
import { V1_REGISTRY } from '../engine/modules';
import type {
  ExecutionResult,
  ModuleRegistry,
  Project,
} from '../engine/types';
import type { LearningSequenceMeta } from './learning-sequence';

export interface DemoProject extends LearningSequenceMeta {
  id: string;
  name: string;
  group?: string;
  summary: string;
  pipeline: string;
  defaultTickedMode?: boolean;
  project: Project;
  layout: Record<string, { x: number; y: number }>;
}

export const demoProjects: DemoProject[] = [
  {
    id: 'toy-rsa',
    name: 'Toy RSA',
    group: 'Number Theory',
    summary: 'A visible RSA round-trip: encrypt a message with one exponent, decrypt with the inverse exponent, all modulo the same n.',
    pipeline: 'HexSource -> ModExp(encrypt) -> ModExp(decrypt) -> BitsToHex -> HexOutput',
    project: {
      modules: [
        { id: 'message', defId: 'HexSource', params: { value: '02' } },
        { id: 'pub-exp', defId: 'HexSource', params: { value: '03' } },
        { id: 'priv-exp', defId: 'HexSource', params: { value: '03' } },
        { id: 'encrypt', defId: 'ModExp', params: { modulus: 15 } },
        { id: 'decrypt', defId: 'ModExp', params: { modulus: 15 } },
        { id: 'hex-out', defId: 'BitsToHex', params: {} },
        { id: 'output', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'message', port: 'out' }, to: { moduleId: 'encrypt', port: 'base' } },
        { from: { moduleId: 'pub-exp', port: 'out' }, to: { moduleId: 'encrypt', port: 'exp' } },
        { from: { moduleId: 'encrypt', port: 'out' }, to: { moduleId: 'decrypt', port: 'base' } },
        { from: { moduleId: 'priv-exp', port: 'out' }, to: { moduleId: 'decrypt', port: 'exp' } },
        { from: { moduleId: 'decrypt', port: 'out' }, to: { moduleId: 'hex-out', port: 'in' } },
        { from: { moduleId: 'hex-out', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      message: { x: 72, y: 88 },
      'pub-exp': { x: 72, y: 232 },
      encrypt: { x: 340, y: 156 },
      'priv-exp': { x: 340, y: 316 },
      decrypt: { x: 600, y: 232 },
      'hex-out': { x: 860, y: 232 },
      output: { x: 1020, y: 232 },
    },
  },
  {
    id: 'diffie-hellman-key-exchange',
    name: 'Diffie-Hellman Key Exchange',
    group: 'Number Theory',
    stage: 'advanced-arithmetic-and-number-theory',
    order: 225,
    recommendedAfter: ['toy-rsa'],
    summary: 'Two visible exponentiation branches exchange public values, then derive the same shared secret without ever transmitting that secret directly.',
    pipeline: 'HexSource(g,a,b) -> ModExp public values -> ModExp shared secrets -> BitsToHex + Equals',
    project: {
      modules: [
        { id: 'generator', defId: 'HexSource', params: { value: '05' } },
        { id: 'alice-private', defId: 'HexSource', params: { value: '06' } },
        { id: 'bob-private', defId: 'HexSource', params: { value: '0F' } },
        { id: 'alice-public', defId: 'ModExp', params: { modulus: 23 } },
        { id: 'bob-public', defId: 'ModExp', params: { modulus: 23 } },
        { id: 'alice-secret', defId: 'ModExp', params: { modulus: 23 } },
        { id: 'bob-secret', defId: 'ModExp', params: { modulus: 23 } },
        { id: 'alice-public-hex', defId: 'BitsToHex', params: {} },
        { id: 'bob-public-hex', defId: 'BitsToHex', params: {} },
        { id: 'alice-secret-hex', defId: 'BitsToHex', params: {} },
        { id: 'bob-secret-hex', defId: 'BitsToHex', params: {} },
        { id: 'alice-public-out', defId: 'HexOutput', params: {} },
        { id: 'bob-public-out', defId: 'HexOutput', params: {} },
        { id: 'alice-secret-out', defId: 'HexOutput', params: {} },
        { id: 'bob-secret-out', defId: 'HexOutput', params: {} },
        { id: 'secrets-match', defId: 'Equals', params: {} },
        { id: 'match-out', defId: 'BitOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'generator', port: 'out' }, to: { moduleId: 'alice-public', port: 'base' } },
        { from: { moduleId: 'generator', port: 'out' }, to: { moduleId: 'bob-public', port: 'base' } },
        { from: { moduleId: 'alice-private', port: 'out' }, to: { moduleId: 'alice-public', port: 'exp' } },
        { from: { moduleId: 'alice-private', port: 'out' }, to: { moduleId: 'alice-secret', port: 'exp' } },
        { from: { moduleId: 'bob-private', port: 'out' }, to: { moduleId: 'bob-public', port: 'exp' } },
        { from: { moduleId: 'bob-private', port: 'out' }, to: { moduleId: 'bob-secret', port: 'exp' } },
        { from: { moduleId: 'alice-public', port: 'out' }, to: { moduleId: 'alice-public-hex', port: 'in' } },
        { from: { moduleId: 'alice-public-hex', port: 'out' }, to: { moduleId: 'alice-public-out', port: 'in' } },
        { from: { moduleId: 'alice-public', port: 'out' }, to: { moduleId: 'bob-secret', port: 'base' } },
        { from: { moduleId: 'bob-public', port: 'out' }, to: { moduleId: 'bob-public-hex', port: 'in' } },
        { from: { moduleId: 'bob-public-hex', port: 'out' }, to: { moduleId: 'bob-public-out', port: 'in' } },
        { from: { moduleId: 'bob-public', port: 'out' }, to: { moduleId: 'alice-secret', port: 'base' } },
        { from: { moduleId: 'alice-secret', port: 'out' }, to: { moduleId: 'alice-secret-hex', port: 'in' } },
        { from: { moduleId: 'alice-secret-hex', port: 'out' }, to: { moduleId: 'alice-secret-out', port: 'in' } },
        { from: { moduleId: 'alice-secret', port: 'out' }, to: { moduleId: 'secrets-match', port: 'a' } },
        { from: { moduleId: 'bob-secret', port: 'out' }, to: { moduleId: 'bob-secret-hex', port: 'in' } },
        { from: { moduleId: 'bob-secret-hex', port: 'out' }, to: { moduleId: 'bob-secret-out', port: 'in' } },
        { from: { moduleId: 'bob-secret', port: 'out' }, to: { moduleId: 'secrets-match', port: 'b' } },
        { from: { moduleId: 'secrets-match', port: 'out' }, to: { moduleId: 'match-out', port: 'in' } },
      ],
    },
    layout: {
      generator: { x: 64, y: 72 },
      'alice-private': { x: 64, y: 228 },
      'bob-private': { x: 64, y: 384 },
      'alice-public': { x: 320, y: 72 },
      'bob-public': { x: 320, y: 384 },
      'alice-public-hex': { x: 560, y: 24 },
      'alice-public-out': { x: 760, y: 24 },
      'bob-public-hex': { x: 560, y: 384 },
      'bob-public-out': { x: 760, y: 384 },
      'alice-secret': { x: 560, y: 156 },
      'bob-secret': { x: 560, y: 540 },
      'alice-secret-hex': { x: 808, y: 156 },
      'alice-secret-out': { x: 1008, y: 156 },
      'bob-secret-hex': { x: 808, y: 540 },
      'bob-secret-out': { x: 1008, y: 540 },
      'secrets-match': { x: 1040, y: 344 },
      'match-out': { x: 1260, y: 344 },
    },
  },
  {
    id: 'key-schedule-workshop',
    name: 'Key Schedule Workshop',
    group: 'Key Schedule',
    summary: 'A visible two-round key schedule that derives distinct round keys from one master key using rotation and XOR with a round constant.',
    pipeline: 'HexSource(master key) -> BitShifter -> XOR(round constant) -> round key branches',
    project: {
      modules: [
        { id: 'master-key', defId: 'HexSource', params: { value: 'A3' } },
        { id: 'data', defId: 'HexSource', params: { value: '5F' } },
        { id: 'round-const', defId: 'HexSource', params: { value: '1B' } },
        { id: 'rotate', defId: 'BitShifter', params: { mode: 'rotate-left', amount: 2 } },
        { id: 'mix', defId: 'XOR', params: {} },
        { id: 'round1-xor', defId: 'XOR', params: {} },
        { id: 'round2-xor', defId: 'XOR', params: {} },
        { id: 'out1-hex', defId: 'BitsToHex', params: {} },
        { id: 'out2-hex', defId: 'BitsToHex', params: {} },
        { id: 'out1', defId: 'HexOutput', params: {} },
        { id: 'out2', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'master-key', port: 'out' }, to: { moduleId: 'round1-xor', port: 'a' } },
        { from: { moduleId: 'data', port: 'out' }, to: { moduleId: 'round1-xor', port: 'b' } },
        { from: { moduleId: 'round1-xor', port: 'out' }, to: { moduleId: 'out1-hex', port: 'in' } },
        { from: { moduleId: 'out1-hex', port: 'out' }, to: { moduleId: 'out1', port: 'in' } },
        { from: { moduleId: 'master-key', port: 'out' }, to: { moduleId: 'rotate', port: 'in' } },
        { from: { moduleId: 'rotate', port: 'out' }, to: { moduleId: 'mix', port: 'a' } },
        { from: { moduleId: 'round-const', port: 'out' }, to: { moduleId: 'mix', port: 'b' } },
        { from: { moduleId: 'mix', port: 'out' }, to: { moduleId: 'round2-xor', port: 'a' } },
        { from: { moduleId: 'data', port: 'out' }, to: { moduleId: 'round2-xor', port: 'b' } },
        { from: { moduleId: 'round2-xor', port: 'out' }, to: { moduleId: 'out2-hex', port: 'in' } },
        { from: { moduleId: 'out2-hex', port: 'out' }, to: { moduleId: 'out2', port: 'in' } },
      ],
    },
    layout: {
      'master-key': { x: 72, y: 88 },
      data: { x: 72, y: 316 },
      'round-const': { x: 72, y: 500 },
      'round1-xor': { x: 340, y: 200 },
      'out1-hex': { x: 540, y: 200 },
      out1: { x: 740, y: 200 },
      rotate: { x: 340, y: 88 },
      mix: { x: 340, y: 430 },
      'round2-xor': { x: 540, y: 380 },
      'out2-hex': { x: 740, y: 380 },
      out2: { x: 940, y: 380 },
    },
  },
  {
    id: 'multiply-compare-unpad',
    name: 'Multiply Compare Unpad',
    group: 'Arithmetic Expansion',
    summary: 'Modular multiplication feeds a threshold comparison while a parallel branch demonstrates pad-then-unpad round-tripping.',
    pipeline: 'HexSource * HexSource -> MulMod -> GreaterThan + BitPad -> BitUnpad',
    project: {
      modules: [
        { id: 'a', defId: 'HexSource', params: { value: '03' } },
        { id: 'b', defId: 'HexSource', params: { value: '05' } },
        { id: 'mul', defId: 'MulMod', params: {} },
        { id: 'threshold', defId: 'HexSource', params: { value: '0A' } },
        { id: 'gt', defId: 'GreaterThan', params: {} },
        { id: 'gt-out', defId: 'BitOutput', params: {} },
        { id: 'pad', defId: 'BitPad', params: { targetWidth: 16 } },
        { id: 'unpad', defId: 'BitUnpad', params: { originalWidth: 8 } },
        { id: 'unpad-out', defId: 'BitsToHex', params: {} },
        { id: 'output', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'a', port: 'out' }, to: { moduleId: 'mul', port: 'a' } },
        { from: { moduleId: 'b', port: 'out' }, to: { moduleId: 'mul', port: 'b' } },
        { from: { moduleId: 'mul', port: 'out' }, to: { moduleId: 'gt', port: 'a' } },
        { from: { moduleId: 'threshold', port: 'out' }, to: { moduleId: 'gt', port: 'b' } },
        { from: { moduleId: 'gt', port: 'out' }, to: { moduleId: 'gt-out', port: 'in' } },
        { from: { moduleId: 'mul', port: 'out' }, to: { moduleId: 'pad', port: 'in' } },
        { from: { moduleId: 'pad', port: 'out' }, to: { moduleId: 'unpad', port: 'in' } },
        { from: { moduleId: 'unpad', port: 'out' }, to: { moduleId: 'unpad-out', port: 'in' } },
        { from: { moduleId: 'unpad-out', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      a: { x: 72, y: 88 },
      b: { x: 72, y: 232 },
      mul: { x: 340, y: 156 },
      threshold: { x: 340, y: 316 },
      gt: { x: 600, y: 232 },
      'gt-out': { x: 860, y: 232 },
      pad: { x: 600, y: 88 },
      unpad: { x: 760, y: 88 },
      'unpad-out': { x: 920, y: 88 },
      output: { x: 1080, y: 88 },
    },
  },
  {
    id: 'visible-message-window',
    name: 'Visible Message Window',
    group: 'Symbol Structure',
    summary: 'One visible message feeds two contiguous symbol windows so downstream branches can read different submessages without hidden chunking.',
    pipeline: 'TextInput -> SymbolWindow / SymbolWindow -> TextOutput comparison',
    project: {
      modules: [
        { id: 'text', defId: 'TextInput', params: { value: 'MATH' } },
        { id: 'window-1', defId: 'SymbolWindow', params: { start: 0, width: 2 } },
        { id: 'window-2', defId: 'SymbolWindow', params: { start: 2, width: 2 } },
        { id: 'out-1', defId: 'TextOutput', params: {} },
        { id: 'out-2', defId: 'TextOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'text', port: 'out' }, to: { moduleId: 'window-1', port: 'in' } },
        { from: { moduleId: 'text', port: 'out' }, to: { moduleId: 'window-2', port: 'in' } },
        { from: { moduleId: 'window-1', port: 'out' }, to: { moduleId: 'out-1', port: 'in' } },
        { from: { moduleId: 'window-2', port: 'out' }, to: { moduleId: 'out-2', port: 'in' } },
      ],
    },
    layout: {
      text: { x: 72, y: 172 },
      'window-1': { x: 372, y: 88 },
      'window-2': { x: 372, y: 256 },
      'out-1': { x: 680, y: 88 },
      'out-2': { x: 680, y: 256 },
    },
  },
  {
    id: 'visible-symbol-scramble',
    name: 'Visible Symbol Scramble',
    group: 'Symbol Permutation',
    summary: 'A direct symbol-order transform that rearranges positions while leaving the symbols themselves unchanged.',
    pipeline: 'TextInput -> SymbolPermutation -> TextOutput',
    project: {
      modules: [
        { id: 'text', defId: 'TextInput', params: { value: 'MATH' } },
        { id: 'permute', defId: 'SymbolPermutation', params: { order: '2,0,3,1' } },
        { id: 'output', defId: 'TextOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'text', port: 'out' }, to: { moduleId: 'permute', port: 'in' } },
        { from: { moduleId: 'permute', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      text: { x: 80, y: 156 },
      permute: { x: 392, y: 156 },
      output: { x: 704, y: 156 },
    },
  },
  {
    id: 'baudot-bridge',
    name: 'Baudot Telegraph',
    group: 'Historical Bridges',
    summary: 'A teleprinter-era 5-bit bridge that begins in Baudot, stays explicit in bits, and returns to readable text.',
    pipeline: 'BaudotSource -> BitsToBaudot -> BaudotOutput',
    project: {
      modules: [
        { id: 'source', defId: 'BaudotSource', params: { value: 'TEST' } },
        { id: 'decode', defId: 'BitsToBaudot', params: {} },
        { id: 'output', defId: 'BaudotOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'decode', port: 'in' } },
        { from: { moduleId: 'decode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      source: { x: 80, y: 156 },
      decode: { x: 392, y: 156 },
      output: { x: 704, y: 156 },
    },
  },
  {
    id: 'lorenz-foundation',
    name: 'Lorenz SZ42 Foundation',
    group: 'Historical Bridges',
    summary: 'A clocked teleprinter-style keystream machine that unmasks one Baudot codeword per tick before decoding it back into text.',
    pipeline: 'Clock -> BaudotSource -> XOR <- LFSR -> BitsToBaudot -> BaudotOutput',
    defaultTickedMode: true,
    project: {
      modules: [
        { id: 'clock', defId: 'Clock', params: { period: 1, offset: 0, length: 5 } },
        { id: 'source', defId: 'BaudotSource', params: { value: 'WCNCE' } },
        {
          id: 'lfsr',
          defId: 'LFSR',
          params: { seed: [1, 1, 1, 0, 0], taps: '1,3', outputLength: 5 },
        },
        { id: 'xor', defId: 'XOR', params: {} },
        { id: 'decode', defId: 'BitsToBaudot', params: {} },
        { id: 'output', defId: 'BaudotOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'lfsr', port: 'clock' } },
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'xor', port: 'a' } },
        { from: { moduleId: 'lfsr', port: 'out' }, to: { moduleId: 'xor', port: 'b' } },
        { from: { moduleId: 'xor', port: 'out' }, to: { moduleId: 'decode', port: 'in' } },
        { from: { moduleId: 'decode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      clock: { x: 40, y: 68 },
      source: { x: 40, y: 236 },
      lfsr: { x: 280, y: 68 },
      xor: { x: 520, y: 152 },
      decode: { x: 760, y: 152 },
      output: { x: 1000, y: 152 },
    },
  },
  {
    id: 'gated-lorenz',
    name: 'Gated Lorenz Wheels',
    group: 'Historical Bridges',
    summary: 'One clocked wheel stream gates a second 5-bit keystream register before each Baudot codeword is unmixed and decoded.',
    pipeline: 'Clock -> Gate LFSR -> Data LFSR -> XOR(BaudotSource) -> BitsToBaudot -> BaudotOutput',
    defaultTickedMode: true,
    project: {
      modules: [
        { id: 'clock', defId: 'Clock', params: { period: 1, offset: 0, length: 5 } },
        { id: 'source', defId: 'BaudotSource', params: { value: 'WCNCE' } },
        {
          id: 'gate',
          defId: 'LFSR',
          params: { seed: [1, 0, 0, 1, 1], taps: '0,2', outputLength: 1 },
        },
        {
          id: 'data',
          defId: 'LFSR',
          params: { seed: [1, 1, 0, 1, 0], taps: '1,3', outputLength: 5 },
        },
        { id: 'xor', defId: 'XOR', params: {} },
        { id: 'decode', defId: 'BitsToBaudot', params: {} },
        { id: 'output', defId: 'BaudotOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'gate', port: 'clock' } },
        { from: { moduleId: 'gate', port: 'out' }, to: { moduleId: 'data', port: 'clock' } },
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'xor', port: 'a' } },
        { from: { moduleId: 'data', port: 'out' }, to: { moduleId: 'xor', port: 'b' } },
        { from: { moduleId: 'xor', port: 'out' }, to: { moduleId: 'decode', port: 'in' } },
        { from: { moduleId: 'decode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      clock: { x: 36, y: 56 },
      source: { x: 36, y: 248 },
      gate: { x: 260, y: 56 },
      data: { x: 500, y: 56 },
      xor: { x: 736, y: 152 },
      decode: { x: 972, y: 152 },
      output: { x: 1208, y: 152 },
    },
  },
  {
    id: 'paired-lorenz',
    name: 'Paired Lorenz Wheels',
    group: 'Historical Bridges',
    summary: 'Two 5-bit wheel streams combine into one teleprinter keystream before each Baudot codeword is unmixed and decoded.',
    pipeline: 'Clock -> Wheel A LFSR + Wheel B LFSR -> XOR -> XOR(BaudotSource) -> BitsToBaudot -> BaudotOutput',
    defaultTickedMode: true,
    project: {
      modules: [
        { id: 'clock', defId: 'Clock', params: { period: 1, offset: 0, length: 5 } },
        { id: 'source', defId: 'BaudotSource', params: { value: 'WCNCE' } },
        {
          id: 'wheel-a',
          defId: 'LFSR',
          params: { seed: [1, 1, 1, 0, 0], taps: '1,3', outputLength: 5 },
        },
        {
          id: 'wheel-b',
          defId: 'LFSR',
          params: { seed: [1, 0, 1, 1, 0], taps: '0,2', outputLength: 5 },
        },
        { id: 'mix', defId: 'XOR', params: {} },
        { id: 'xor', defId: 'XOR', params: {} },
        { id: 'decode', defId: 'BitsToBaudot', params: {} },
        { id: 'output', defId: 'BaudotOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'wheel-a', port: 'clock' } },
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'wheel-b', port: 'clock' } },
        { from: { moduleId: 'wheel-a', port: 'out' }, to: { moduleId: 'mix', port: 'a' } },
        { from: { moduleId: 'wheel-b', port: 'out' }, to: { moduleId: 'mix', port: 'b' } },
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'xor', port: 'a' } },
        { from: { moduleId: 'mix', port: 'out' }, to: { moduleId: 'xor', port: 'b' } },
        { from: { moduleId: 'xor', port: 'out' }, to: { moduleId: 'decode', port: 'in' } },
        { from: { moduleId: 'decode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      clock: { x: 28, y: 56 },
      source: { x: 28, y: 248 },
      'wheel-a': { x: 252, y: 56 },
      'wheel-b': { x: 252, y: 248 },
      mix: { x: 500, y: 152 },
      xor: { x: 748, y: 152 },
      decode: { x: 996, y: 152 },
      output: { x: 1244, y: 152 },
    },
  },
  {
    id: 'banked-lorenz',
    name: 'Banked Lorenz Control',
    group: 'Historical Bridges',
    summary: 'Two control wheels combine into one explicit gate signal that decides when the 5-bit data wheel is allowed to advance.',
    pipeline: 'Clock -> Control Wheels -> XOR Gate -> Data LFSR -> XOR(BaudotSource) -> BitsToBaudot -> BaudotOutput',
    defaultTickedMode: true,
    project: {
      modules: [
        { id: 'clock', defId: 'Clock', params: { period: 1, offset: 0, length: 5 } },
        { id: 'source', defId: 'BaudotSource', params: { value: 'WCNCE' } },
        {
          id: 'control-a',
          defId: 'LFSR',
          params: { seed: [1, 0, 0, 1, 1], taps: '0,2', outputLength: 1 },
        },
        {
          id: 'control-b',
          defId: 'LFSR',
          params: { seed: [1, 1, 0, 0, 1], taps: '1,3', outputLength: 1 },
        },
        {
          id: 'data',
          defId: 'LFSR',
          params: { seed: [1, 1, 0, 1, 0], taps: '1,3', outputLength: 5 },
        },
        { id: 'gate-mix', defId: 'XOR', params: {} },
        { id: 'xor', defId: 'XOR', params: {} },
        { id: 'decode', defId: 'BitsToBaudot', params: {} },
        { id: 'output', defId: 'BaudotOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'control-a', port: 'clock' } },
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'control-b', port: 'clock' } },
        { from: { moduleId: 'control-a', port: 'out' }, to: { moduleId: 'gate-mix', port: 'a' } },
        { from: { moduleId: 'control-b', port: 'out' }, to: { moduleId: 'gate-mix', port: 'b' } },
        { from: { moduleId: 'gate-mix', port: 'out' }, to: { moduleId: 'data', port: 'clock' } },
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'xor', port: 'a' } },
        { from: { moduleId: 'data', port: 'out' }, to: { moduleId: 'xor', port: 'b' } },
        { from: { moduleId: 'xor', port: 'out' }, to: { moduleId: 'decode', port: 'in' } },
        { from: { moduleId: 'decode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      clock: { x: 28, y: 56 },
      source: { x: 28, y: 248 },
      'control-a': { x: 252, y: 40 },
      'control-b': { x: 252, y: 168 },
      'gate-mix': { x: 500, y: 104 },
      data: { x: 748, y: 40 },
      xor: { x: 996, y: 152 },
      decode: { x: 1244, y: 152 },
      output: { x: 1492, y: 152 },
    },
  },
  {
    id: 'bridge',
    name: 'Bridge Pipeline',
    group: 'Foundations',
    summary: 'A minimal symbol-to-bits-to-symbol run that proves the engine/UI bridge.',
    pipeline: 'TextInput -> SymbolToBits -> XOR -> BitsToSymbol -> TextOutput',
    project: {
      modules: [
        { id: 'text', defId: 'TextInput', params: { value: 'M' } },
        { id: 'key', defId: 'BitSource', params: { stream: [0, 0, 0, 1, 1] } },
        { id: 'encode', defId: 'SymbolToBits', params: {} },
        { id: 'xor', defId: 'XOR', params: {} },
        { id: 'decode', defId: 'BitsToSymbol', params: {} },
        { id: 'output', defId: 'TextOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'text', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'xor', port: 'a' } },
        { from: { moduleId: 'key', port: 'out' }, to: { moduleId: 'xor', port: 'b' } },
        { from: { moduleId: 'xor', port: 'out' }, to: { moduleId: 'decode', port: 'in' } },
        { from: { moduleId: 'decode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      text: { x: 28, y: 72 },
      key: { x: 28, y: 262 },
      encode: { x: 240, y: 72 },
      xor: { x: 452, y: 162 },
      decode: { x: 664, y: 72 },
      output: { x: 876, y: 72 },
    },
  },
  {
    id: 'modern',
    name: 'Modern Toy Round',
    group: 'Foundations',
    summary: 'A small bit-domain toy round using permutation and shifting before XOR.',
    pipeline: 'TextInput -> SymbolToBits -> Permutation -> BitShifter -> XOR -> BitsToSymbol -> TextOutput',
    project: {
      modules: [
        { id: 'text', defId: 'TextInput', params: { value: 'C' } },
        { id: 'encode', defId: 'SymbolToBits', params: {} },
        { id: 'permute', defId: 'Permutation', params: { order: '2,0,4,1,3' } },
        { id: 'shift', defId: 'BitShifter', params: { amount: 1, mode: 'rotate-left' } },
        { id: 'key', defId: 'BitSource', params: { stream: [1, 0, 1, 0, 1] } },
        { id: 'xor', defId: 'XOR', params: {} },
        { id: 'decode', defId: 'BitsToSymbol', params: {} },
        { id: 'output', defId: 'TextOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'text', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'permute', port: 'in' } },
        { from: { moduleId: 'permute', port: 'out' }, to: { moduleId: 'shift', port: 'in' } },
        { from: { moduleId: 'shift', port: 'out' }, to: { moduleId: 'xor', port: 'a' } },
        { from: { moduleId: 'key', port: 'out' }, to: { moduleId: 'xor', port: 'b' } },
        { from: { moduleId: 'xor', port: 'out' }, to: { moduleId: 'decode', port: 'in' } },
        { from: { moduleId: 'decode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      text: { x: 24, y: 136 },
      encode: { x: 184, y: 136 },
      permute: { x: 344, y: 136 },
      shift: { x: 504, y: 136 },
      key: { x: 504, y: 304 },
      xor: { x: 664, y: 220 },
      decode: { x: 824, y: 136 },
      output: { x: 984, y: 136 },
    },
  },
  {
    id: 'beyond-xor',
    name: 'Beyond XOR',
    group: 'Foundations',
    summary: 'A visible word-mixing machine that uses modular addition, rotation, masking, and XOR instead of relying on XOR alone.',
    pipeline: 'HexSource + HexSource -> ADD mod 2^n -> BitShifter -> AND(mask) -> XOR(key) -> BitsToHex -> HexOutput',
    project: {
      modules: [
        { id: 'left', defId: 'HexSource', params: { value: 'A3' } },
        { id: 'right', defId: 'HexSource', params: { value: '19' } },
        { id: 'add', defId: 'AddMod', params: {} },
        { id: 'rotate', defId: 'BitShifter', params: { amount: 2, mode: 'rotate-left' } },
        { id: 'mask', defId: 'BitSource', params: { stream: [1, 1, 1, 1, 0, 0, 0, 0] } },
        { id: 'and', defId: 'AND', params: {} },
        { id: 'key', defId: 'BitSource', params: { stream: [0, 1, 0, 1, 1, 0, 1, 0] } },
        { id: 'xor', defId: 'XOR', params: {} },
        { id: 'encode', defId: 'BitsToHex', params: {} },
        { id: 'output', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'left', port: 'out' }, to: { moduleId: 'add', port: 'a' } },
        { from: { moduleId: 'right', port: 'out' }, to: { moduleId: 'add', port: 'b' } },
        { from: { moduleId: 'add', port: 'out' }, to: { moduleId: 'rotate', port: 'in' } },
        { from: { moduleId: 'rotate', port: 'out' }, to: { moduleId: 'and', port: 'a' } },
        { from: { moduleId: 'mask', port: 'out' }, to: { moduleId: 'and', port: 'b' } },
        { from: { moduleId: 'and', port: 'out' }, to: { moduleId: 'xor', port: 'a' } },
        { from: { moduleId: 'key', port: 'out' }, to: { moduleId: 'xor', port: 'b' } },
        { from: { moduleId: 'xor', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      left: { x: 24, y: 92 },
      right: { x: 24, y: 248 },
      add: { x: 220, y: 168 },
      rotate: { x: 416, y: 168 },
      mask: { x: 416, y: 324 },
      and: { x: 612, y: 168 },
      key: { x: 612, y: 324 },
      xor: { x: 808, y: 168 },
      encode: { x: 1004, y: 168 },
      output: { x: 1200, y: 168 },
    },
  },
  {
    id: 'bypass-workshop',
    name: 'Bypass Workshop',
    group: 'Modern Rounds',
    summary: 'A visible shift stage can be turned off without deleting it from the chain, making it easy to compare one machine with and without that transform.',
    pipeline: 'HexSource -> BitShifter -> BitsToHex -> HexOutput',
    project: {
      modules: [
        { id: 'source', defId: 'HexSource', params: { value: 'A3' } },
        { id: 'shift', defId: 'BitShifter', params: { amount: 2, mode: 'rotate-left' } },
        { id: 'encode', defId: 'BitsToHex', params: {} },
        { id: 'output', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'shift', port: 'in' } },
        { from: { moduleId: 'shift', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      source: { x: 72, y: 156 },
      shift: { x: 360, y: 156 },
      encode: { x: 648, y: 156 },
      output: { x: 936, y: 156 },
    },
  },
  {
    id: 'split-transform-rejoin',
    name: 'Split Transform Rejoin',
    group: 'Block Framing',
    summary: 'A 16-bit hex input is split into two 8-bit halves, each is transformed independently, and the halves are rejoined into one visible output.',
    pipeline: 'HexSource -> BitSplit -> XOR(left key) + XOR(right key) -> BitJoin -> BitsToHex -> HexOutput',
    project: {
      modules: [
        { id: 'source', defId: 'HexSource', params: { value: 'A3F1' } },
        { id: 'split', defId: 'BitSplit', params: { leftWidth: 8 } },
        { id: 'left-key', defId: 'BitSource', params: { stream: [1, 0, 1, 0, 1, 0, 1, 0] } },
        { id: 'right-key', defId: 'BitSource', params: { stream: [0, 1, 0, 1, 0, 1, 0, 1] } },
        { id: 'left-xor', defId: 'XOR', params: {} },
        { id: 'right-xor', defId: 'XOR', params: {} },
        { id: 'join', defId: 'BitJoin', params: {} },
        { id: 'encode', defId: 'BitsToHex', params: {} },
        { id: 'output', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'split', port: 'in' } },
        { from: { moduleId: 'split', port: 'left' }, to: { moduleId: 'left-xor', port: 'a' } },
        { from: { moduleId: 'left-key', port: 'out' }, to: { moduleId: 'left-xor', port: 'b' } },
        { from: { moduleId: 'split', port: 'right' }, to: { moduleId: 'right-xor', port: 'a' } },
        { from: { moduleId: 'right-key', port: 'out' }, to: { moduleId: 'right-xor', port: 'b' } },
        { from: { moduleId: 'left-xor', port: 'out' }, to: { moduleId: 'join', port: 'a' } },
        { from: { moduleId: 'right-xor', port: 'out' }, to: { moduleId: 'join', port: 'b' } },
        { from: { moduleId: 'join', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      source: { x: 24, y: 168 },
      split: { x: 220, y: 168 },
      'left-key': { x: 416, y: 56 },
      'right-key': { x: 416, y: 280 },
      'left-xor': { x: 612, y: 92 },
      'right-xor': { x: 612, y: 244 },
      join: { x: 808, y: 168 },
      encode: { x: 1004, y: 168 },
      output: { x: 1200, y: 168 },
    },
  },
  {
    id: 'pad-and-split',
    name: 'Pad and Split',
    group: 'Block Framing',
    summary: 'A short 8-bit input is padded to 16 bits, then split into two halves for independent processing — showing how padding prepares undersized messages for fixed-width block pipelines.',
    pipeline: 'HexSource -> BitPad(16) -> BitSplit(8) -> XOR(left key) + XOR(right key) -> BitJoin -> BitsToHex -> HexOutput',
    project: {
      modules: [
        { id: 'source', defId: 'HexSource', params: { value: 'C7' } },
        { id: 'pad', defId: 'BitPad', params: { targetWidth: 16, side: 'right', padBit: '0' } },
        { id: 'split', defId: 'BitSplit', params: { leftWidth: 8 } },
        { id: 'left-key', defId: 'BitSource', params: { stream: [1, 0, 1, 0, 1, 0, 1, 0] } },
        { id: 'right-key', defId: 'BitSource', params: { stream: [0, 1, 0, 1, 0, 1, 0, 1] } },
        { id: 'left-xor', defId: 'XOR', params: {} },
        { id: 'right-xor', defId: 'XOR', params: {} },
        { id: 'join', defId: 'BitJoin', params: {} },
        { id: 'encode', defId: 'BitsToHex', params: {} },
        { id: 'output', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'pad', port: 'in' } },
        { from: { moduleId: 'pad', port: 'out' }, to: { moduleId: 'split', port: 'in' } },
        { from: { moduleId: 'split', port: 'left' }, to: { moduleId: 'left-xor', port: 'a' } },
        { from: { moduleId: 'left-key', port: 'out' }, to: { moduleId: 'left-xor', port: 'b' } },
        { from: { moduleId: 'split', port: 'right' }, to: { moduleId: 'right-xor', port: 'a' } },
        { from: { moduleId: 'right-key', port: 'out' }, to: { moduleId: 'right-xor', port: 'b' } },
        { from: { moduleId: 'left-xor', port: 'out' }, to: { moduleId: 'join', port: 'a' } },
        { from: { moduleId: 'right-xor', port: 'out' }, to: { moduleId: 'join', port: 'b' } },
        { from: { moduleId: 'join', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      source: { x: 24, y: 168 },
      pad: { x: 180, y: 168 },
      split: { x: 336, y: 168 },
      'left-key': { x: 532, y: 56 },
      'right-key': { x: 532, y: 280 },
      'left-xor': { x: 728, y: 92 },
      'right-xor': { x: 728, y: 244 },
      join: { x: 924, y: 168 },
      encode: { x: 1120, y: 168 },
      output: { x: 1316, y: 168 },
    },
  },
  {
    id: 'counter-pulse-gate',
    name: 'Counter Pulse Gate',
    group: 'Control Foundations',
    summary: 'A visible counter is compared against a fixed threshold word, and that comparison decides when a downstream keystream register is allowed to advance.',
    pipeline: 'Clock -> Counter -> AtLeast(threshold) -> Gate(clock pulse) -> LFSR -> BitsToSymbol -> TextOutput',
    defaultTickedMode: true,
    project: {
      modules: [
        { id: 'clock', defId: 'Clock', params: { period: 1, offset: 0, length: 8 } },
        { id: 'counter', defId: 'Counter', params: { width: 5, value: 0, step: 1 } },
        { id: 'threshold', defId: 'KeyInput', params: { value: 'D' } },
        { id: 'threshold-bits', defId: 'SymbolToBits', params: {} },
        { id: 'atleast', defId: 'AtLeast', params: {} },
        { id: 'gate', defId: 'Gate', params: {} },
        {
          id: 'data',
          defId: 'LFSR',
          params: { seed: [1, 0, 0, 1, 1], taps: '0,2', outputLength: 5 },
        },
        { id: 'decode', defId: 'BitsToSymbol', params: {} },
        { id: 'output', defId: 'TextOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'counter', port: 'clock' } },
        { from: { moduleId: 'threshold', port: 'out' }, to: { moduleId: 'threshold-bits', port: 'in' } },
        { from: { moduleId: 'counter', port: 'out' }, to: { moduleId: 'atleast', port: 'a' } },
        { from: { moduleId: 'threshold-bits', port: 'out' }, to: { moduleId: 'atleast', port: 'b' } },
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'gate', port: 'in' } },
        { from: { moduleId: 'atleast', port: 'out' }, to: { moduleId: 'gate', port: 'control' } },
        { from: { moduleId: 'gate', port: 'out' }, to: { moduleId: 'data', port: 'clock' } },
        { from: { moduleId: 'data', port: 'out' }, to: { moduleId: 'decode', port: 'in' } },
        { from: { moduleId: 'decode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      clock: { x: 36, y: 60 },
      counter: { x: 252, y: 60 },
      threshold: { x: 252, y: 244 },
      'threshold-bits': { x: 476, y: 244 },
      atleast: { x: 700, y: 152 },
      gate: { x: 924, y: 152 },
      data: { x: 1148, y: 60 },
      decode: { x: 1372, y: 60 },
      output: { x: 1596, y: 60 },
    },
  },
  {
    id: 'packaged-iterated-rounds',
    name: 'Packaged Iterated Rounds',
    group: 'Modern Rounds',
    summary: 'A two-round byte machine packaged as one reusable composite so repeated round structure stays explicit but compact.',
    pipeline: 'HexSource -> IteratedByteRoundsComposite -> BitsToHex -> HexOutput',
    project: {
      modules: [
        { id: 'source', defId: 'HexSource', params: { value: 'A3' } },
        { id: 'rounds', defId: 'ByteRoundIterator', params: {} },
        { id: 'encode', defId: 'BitsToHex', params: {} },
        { id: 'output', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'rounds', port: 'in' } },
        { from: { moduleId: 'rounds', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      source: { x: 48, y: 156 },
      rounds: { x: 372, y: 156 },
      encode: { x: 696, y: 156 },
      output: { x: 1020, y: 156 },
    },
  },
  {
    id: 'iterated-byte-rounds',
    name: 'Iterated Byte Rounds',
    group: 'Modern Rounds',
    summary: 'A byte-oriented machine that reuses the same round composite twice instead of hand-wiring each round from scratch.',
    pipeline: 'HexSource -> ByteRoundComposite -> ByteRoundComposite -> BitsToHex -> HexOutput',
    project: {
      modules: [
        { id: 'source', defId: 'HexSource', params: { value: 'A3' } },
        { id: 'round-1', defId: 'ByteRoundComposite', params: {} },
        { id: 'round-2', defId: 'ByteRoundComposite', params: {} },
        { id: 'encode', defId: 'BitsToHex', params: {} },
        { id: 'output', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'round-1', port: 'in' } },
        { from: { moduleId: 'round-1', port: 'out' }, to: { moduleId: 'round-2', port: 'in' } },
        { from: { moduleId: 'round-2', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      source: { x: 48, y: 156 },
      'round-1': { x: 292, y: 156 },
      'round-2': { x: 536, y: 156 },
      encode: { x: 780, y: 156 },
      output: { x: 1024, y: 156 },
    },
  },
  {
    id: 'keyed-byte-rounds',
    name: 'Scheduled Byte Rounds',
    group: 'Modern Rounds',
    summary: 'Two visible sub-keys feed two keyed byte rounds so repeated-round structure stays explicit before any iterator-aware key schedule exists.',
    pipeline: 'HexSource + Round Keys -> KeyedByteRound -> KeyedByteRound -> BitsToHex -> HexOutput',
    project: {
      modules: [
        { id: 'source', defId: 'HexSource', params: { value: 'A3' } },
        { id: 'key-1', defId: 'HexSource', params: { value: '1C' } },
        { id: 'key-2', defId: 'HexSource', params: { value: 'E7' } },
        { id: 'round-1', defId: 'KeyedByteRoundComposite', params: {} },
        { id: 'round-2', defId: 'KeyedByteRoundComposite', params: {} },
        { id: 'encode', defId: 'BitsToHex', params: {} },
        { id: 'output', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'round-1', port: 'in' } },
        { from: { moduleId: 'key-1', port: 'out' }, to: { moduleId: 'round-1', port: 'key' } },
        { from: { moduleId: 'round-1', port: 'out' }, to: { moduleId: 'round-2', port: 'in' } },
        { from: { moduleId: 'key-2', port: 'out' }, to: { moduleId: 'round-2', port: 'key' } },
        { from: { moduleId: 'round-2', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      source: { x: 32, y: 152 },
      'key-1': { x: 32, y: 40 },
      'key-2': { x: 312, y: 40 },
      'round-1': { x: 312, y: 152 },
      'round-2': { x: 592, y: 152 },
      encode: { x: 872, y: 152 },
      output: { x: 1152, y: 152 },
    },
  },
  {
    id: 'visible-subkey-bus',
    name: 'Visible Sub-Key Bus',
    group: 'Modern Rounds',
    summary: 'One visible key bus is sliced into two explicit sub-keys so each keyed round can read a different window without iterator magic.',
    pipeline: 'HexSource + Key Bus -> BitWindow -> KeyedByteRound -> BitWindow -> KeyedByteRound -> BitsToHex -> HexOutput',
    project: {
      modules: [
        { id: 'source', defId: 'HexSource', params: { value: 'A3' } },
        { id: 'keybus', defId: 'HexSource', params: { value: '1CE7' } },
        { id: 'window-1', defId: 'BitWindow', params: { start: 0, width: 8 } },
        { id: 'window-2', defId: 'BitWindow', params: { start: 8, width: 8 } },
        { id: 'round-1', defId: 'KeyedByteRoundComposite', params: {} },
        { id: 'round-2', defId: 'KeyedByteRoundComposite', params: {} },
        { id: 'encode', defId: 'BitsToHex', params: {} },
        { id: 'output', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'round-1', port: 'in' } },
        { from: { moduleId: 'keybus', port: 'out' }, to: { moduleId: 'window-1', port: 'in' } },
        { from: { moduleId: 'keybus', port: 'out' }, to: { moduleId: 'window-2', port: 'in' } },
        { from: { moduleId: 'window-1', port: 'out' }, to: { moduleId: 'round-1', port: 'key' } },
        { from: { moduleId: 'round-1', port: 'out' }, to: { moduleId: 'round-2', port: 'in' } },
        { from: { moduleId: 'window-2', port: 'out' }, to: { moduleId: 'round-2', port: 'key' } },
        { from: { moduleId: 'round-2', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      source: { x: 32, y: 184 },
      keybus: { x: 32, y: 40 },
      'window-1': { x: 292, y: 40 },
      'window-2': { x: 572, y: 40 },
      'round-1': { x: 292, y: 184 },
      'round-2': { x: 572, y: 184 },
      encode: { x: 852, y: 184 },
      output: { x: 1132, y: 184 },
    },
  },
  {
    id: 'keyed-byte-iterator',
    name: 'Scheduled Byte Iterator',
    group: 'Modern Rounds',
    summary: 'A bounded keyed iterator splits one visible key bus into round-sized sub-keys and feeds them across the unrolled round chain.',
    pipeline: 'HexSource + Key Bus -> KeyedByteRoundIterator -> BitsToHex -> HexOutput',
    project: {
      modules: [
        { id: 'source', defId: 'HexSource', params: { value: 'A3' } },
        { id: 'keybus', defId: 'HexSource', params: { value: '1CE7' } },
        { id: 'rounds', defId: 'KeyedByteRoundIterator', params: {} },
        { id: 'encode', defId: 'BitsToHex', params: {} },
        { id: 'output', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'rounds', port: 'in' } },
        { from: { moduleId: 'keybus', port: 'out' }, to: { moduleId: 'rounds', port: 'key' } },
        { from: { moduleId: 'rounds', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      source: { x: 40, y: 160 },
      keybus: { x: 40, y: 48 },
      rounds: { x: 360, y: 160 },
      encode: { x: 680, y: 160 },
      output: { x: 1000, y: 160 },
    },
  },
  {
    id: 'feistel-network',
    name: 'Feistel Network',
    group: 'Modern Rounds',
    summary: 'A small keyed Feistel network that splits a byte into left and right halves, transforms the right half, recombines the result, and iterates that structure visibly.',
    pipeline: 'HexSource + Key Bus -> FeistelRoundIterator -> BitsToHex -> HexOutput',
    project: {
      modules: [
        { id: 'source', defId: 'HexSource', params: { value: 'A3' } },
        { id: 'keybus', defId: 'HexSource', params: { value: '1C' } },
        { id: 'rounds', defId: 'FeistelRoundIterator', params: { iterationCount: 2 } },
        { id: 'encode', defId: 'BitsToHex', params: {} },
        { id: 'output', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'rounds', port: 'in' } },
        { from: { moduleId: 'keybus', port: 'out' }, to: { moduleId: 'rounds', port: 'key' } },
        { from: { moduleId: 'rounds', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      source: { x: 40, y: 160 },
      keybus: { x: 40, y: 48 },
      rounds: { x: 360, y: 160 },
      encode: { x: 680, y: 160 },
      output: { x: 1000, y: 160 },
    },
  },
  {
    id: 'protocol-material-mixer',
    name: 'Protocol Material Mixer',
    group: 'Protocol Materials',
    summary: 'A framed byte-sized message is padded, split, then mixed with an explicit IV on one branch and a visible key on the other so context stays legible on the graph.',
    pipeline: 'HexSource -> BitPad -> BitSplit -> XOR(IV) + XOR(Key) -> BitJoin -> BitsToHex -> HexOutput',
    project: {
      modules: [
        { id: 'message', defId: 'HexSource', params: { value: 'A3' } },
        { id: 'pad', defId: 'BitPad', params: { targetWidth: 16, side: 'right', padBit: '0' } },
        { id: 'split', defId: 'BitSplit', params: { leftWidth: 8 } },
        { id: 'iv', defId: 'IV', params: { value: '1C', width: 8 } },
        { id: 'key', defId: 'HexSource', params: { value: '55' } },
        { id: 'left-xor', defId: 'XOR', params: {} },
        { id: 'right-xor', defId: 'XOR', params: {} },
        { id: 'join', defId: 'BitJoin', params: {} },
        { id: 'encode', defId: 'BitsToHex', params: {} },
        { id: 'output', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'message', port: 'out' }, to: { moduleId: 'pad', port: 'in' } },
        { from: { moduleId: 'pad', port: 'out' }, to: { moduleId: 'split', port: 'in' } },
        { from: { moduleId: 'split', port: 'left' }, to: { moduleId: 'left-xor', port: 'a' } },
        { from: { moduleId: 'iv', port: 'out' }, to: { moduleId: 'left-xor', port: 'b' } },
        { from: { moduleId: 'split', port: 'right' }, to: { moduleId: 'right-xor', port: 'a' } },
        { from: { moduleId: 'key', port: 'out' }, to: { moduleId: 'right-xor', port: 'b' } },
        { from: { moduleId: 'left-xor', port: 'out' }, to: { moduleId: 'join', port: 'a' } },
        { from: { moduleId: 'right-xor', port: 'out' }, to: { moduleId: 'join', port: 'b' } },
        { from: { moduleId: 'join', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      message: { x: 40, y: 156 },
      pad: { x: 260, y: 156 },
      split: { x: 500, y: 156 },
      iv: { x: 500, y: 44 },
      key: { x: 500, y: 284 },
      'left-xor': { x: 760, y: 92 },
      'right-xor': { x: 760, y: 220 },
      join: { x: 1020, y: 156 },
      encode: { x: 1280, y: 156 },
      output: { x: 1540, y: 156 },
    },
  },
  {
    id: 'byte-round',
    name: 'Byte S-Box Round',
    group: 'Modern Rounds',
    summary: 'An 8-bit substitution and permutation round that stays fully in the bit domain.',
    pipeline: 'BitSource -> SBox(256) -> Permutation -> BitOutput',
    project: {
      modules: [
        { id: 'source', defId: 'BitSource', params: { stream: [1, 0, 1, 0, 1, 1, 0, 0] } },
        {
          id: 'sbox',
          defId: 'SBox',
          params: {
            table: Array.from({ length: 256 }, (_, index) => 255 - index).join(','),
          },
        },
        { id: 'permute', defId: 'Permutation', params: { order: '7,6,5,4,3,2,1,0' } },
        { id: 'output', defId: 'BitOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'sbox', port: 'in' } },
        { from: { moduleId: 'sbox', port: 'out' }, to: { moduleId: 'permute', port: 'in' } },
        { from: { moduleId: 'permute', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      source: { x: 48, y: 156 },
      sbox: { x: 292, y: 156 },
      permute: { x: 536, y: 156 },
      output: { x: 780, y: 156 },
    },
  },
  {
    id: 'hex-round',
    name: 'Hex Byte Round',
    group: 'Bridge Rounds',
    summary: 'A byte-oriented round that starts from hex, stays in bits for substitution/permutation, and returns to hex.',
    pipeline: 'HexSource -> SBox(256) -> Permutation -> BitsToHex -> HexOutput',
    project: {
      modules: [
        { id: 'source', defId: 'HexSource', params: { value: 'A3' } },
        {
          id: 'sbox',
          defId: 'SBox',
          params: {
            table: Array.from({ length: 256 }, (_, index) => 255 - index).join(','),
          },
        },
        { id: 'permute', defId: 'Permutation', params: { order: '7,6,5,4,3,2,1,0' } },
        { id: 'encode', defId: 'BitsToHex', params: {} },
        { id: 'output', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'sbox', port: 'in' } },
        { from: { moduleId: 'sbox', port: 'out' }, to: { moduleId: 'permute', port: 'in' } },
        { from: { moduleId: 'permute', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      source: { x: 48, y: 156 },
      sbox: { x: 252, y: 156 },
      permute: { x: 456, y: 156 },
      encode: { x: 660, y: 156 },
      output: { x: 864, y: 156 },
    },
  },
  {
    id: 'ascii-round',
    name: 'ASCII Byte Round',
    group: 'Bridge Rounds',
    summary: 'A byte-oriented round that begins with ASCII text, transforms it in bits, and returns to ASCII.',
    pipeline: 'AsciiSource -> SBox(256) -> Permutation -> BitsToAscii -> TextOutput',
    project: {
      modules: [
        { id: 'source', defId: 'AsciiSource', params: { value: 'A' } },
        {
          id: 'sbox',
          defId: 'SBox',
          params: {
            table: Array.from({ length: 256 }, (_, index) => 255 - index).join(','),
          },
        },
        { id: 'permute', defId: 'Permutation', params: { order: '7,6,5,4,3,2,1,0' } },
        { id: 'encode', defId: 'BitsToAscii', params: {} },
        { id: 'output', defId: 'TextOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'sbox', port: 'in' } },
        { from: { moduleId: 'sbox', port: 'out' }, to: { moduleId: 'permute', port: 'in' } },
        { from: { moduleId: 'permute', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      source: { x: 48, y: 156 },
      sbox: { x: 252, y: 156 },
      permute: { x: 456, y: 156 },
      encode: { x: 660, y: 156 },
      output: { x: 864, y: 156 },
    },
  },
  {
    id: 'toy-compression-hash',
    name: 'Toy Compression Hash',
    group: 'Hash Foundations',
    summary: 'Two visible message bytes are mixed separately, XOR-compressed into one digest byte, and then diffused through repeated digest rounds.',
    pipeline: 'HexSource + HexSource -> ToyCompressionHashComposite -> BitsToHex -> HexOutput',
    project: {
      modules: [
        { id: 'left-source', defId: 'HexSource', params: { value: 'A3' } },
        { id: 'right-source', defId: 'HexSource', params: { value: '6F' } },
        { id: 'hash', defId: 'ToyCompressionHashComposite', params: {} },
        { id: 'encode', defId: 'BitsToHex', params: {} },
        { id: 'output', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'left-source', port: 'out' }, to: { moduleId: 'hash', port: 'left' } },
        { from: { moduleId: 'right-source', port: 'out' }, to: { moduleId: 'hash', port: 'right' } },
        { from: { moduleId: 'hash', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      'left-source': { x: 44, y: 108 },
      'right-source': { x: 44, y: 236 },
      hash: { x: 352, y: 172 },
      encode: { x: 660, y: 172 },
      output: { x: 968, y: 172 },
    },
  },
  {
    id: 'hash-digest-round',
    name: 'Hash Digest Round',
    group: 'Hash Foundations',
    summary: 'A single digest round that substitutes, rotates, and constant-mixes one byte so students can hear the effect of mode changes before stacking rounds.',
    pipeline: 'HexSource -> HashDigestRoundComposite -> BitsToHex -> HexOutput',
    project: {
      modules: [
        { id: 'source', defId: 'HexSource', params: { value: 'A3' } },
        { id: 'digest', defId: 'HashDigestRoundComposite', params: {} },
        { id: 'encode', defId: 'BitsToHex', params: {} },
        { id: 'output', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'source', port: 'out' }, to: { moduleId: 'digest', port: 'in' } },
        { from: { moduleId: 'digest', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      source: { x: 48, y: 156 },
      digest: { x: 336, y: 156 },
      encode: { x: 624, y: 156 },
      output: { x: 912, y: 156 },
    },
  },
  {
    id: 'toy-sponge-hash',
    name: 'Toy Sponge Hash',
    group: 'Hash Foundations',
    summary: 'Two visible message bytes are absorbed one at a time into a 16-bit sponge state, mixed after each absorb, and then squeezed back down to one digest byte.',
    pipeline: 'HexSource + HexSource -> ToySpongeHashComposite -> BitsToHex -> HexOutput',
    project: {
      modules: [
        { id: 'left-source', defId: 'HexSource', params: { value: 'AA' } },
        { id: 'right-source', defId: 'HexSource', params: { value: 'BB' } },
        { id: 'sponge', defId: 'ToySpongeHashComposite', params: {} },
        { id: 'encode', defId: 'BitsToHex', params: {} },
        { id: 'output', defId: 'HexOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'left-source', port: 'out' }, to: { moduleId: 'sponge', port: 'left' } },
        { from: { moduleId: 'right-source', port: 'out' }, to: { moduleId: 'sponge', port: 'right' } },
        { from: { moduleId: 'sponge', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      'left-source': { x: 44, y: 108 },
      'right-source': { x: 44, y: 236 },
      sponge: { x: 352, y: 172 },
      encode: { x: 660, y: 172 },
      output: { x: 968, y: 172 },
    },
  },
  {
    id: 'sequential',
    name: 'Sequential Heart',
    group: 'Sequential',
    summary: 'A clocked keystream pipeline that turns state changes into a symbol stream over time.',
    pipeline: 'Clock -> LFSR -> BitsToSymbol -> TextOutput',
    defaultTickedMode: true,
    project: {
      modules: [
        { id: 'clock', defId: 'Clock', params: { period: 1, offset: 0, length: 8 } },
        {
          id: 'lfsr',
          defId: 'LFSR',
          params: { seed: [1, 0, 1, 1, 0], taps: '0,2', outputLength: 5 },
        },
        { id: 'decode', defId: 'BitsToSymbol', params: {} },
        { id: 'output', defId: 'TextOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'lfsr', port: 'clock' } },
        { from: { moduleId: 'lfsr', port: 'out' }, to: { moduleId: 'decode', port: 'in' } },
        { from: { moduleId: 'decode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      clock: { x: 48, y: 156 },
      lfsr: { x: 292, y: 156 },
      decode: { x: 536, y: 156 },
      output: { x: 780, y: 156 },
    },
  },
  {
    id: 'keystream',
    name: 'Modern Keystream',
    group: 'Sequential',
    summary: 'A clocked LFSR keystream XORs a plaintext bit stream without ever leaving the bit domain.',
    pipeline: 'Clock -> LFSR -> XOR(BitSource) -> BitOutput',
    defaultTickedMode: true,
    project: {
      modules: [
        { id: 'clock', defId: 'Clock', params: { period: 1, offset: 0, length: 8 } },
        { id: 'plain', defId: 'BitSource', params: { stream: [1, 0, 1, 1, 0, 0, 1, 0] } },
        {
          id: 'lfsr',
          defId: 'LFSR',
          params: { seed: [1, 0, 1, 1, 0], taps: '0,2', outputLength: 1 },
        },
        { id: 'xor', defId: 'XOR', params: {} },
        { id: 'output', defId: 'BitOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'lfsr', port: 'clock' } },
        { from: { moduleId: 'plain', port: 'out' }, to: { moduleId: 'xor', port: 'a' } },
        { from: { moduleId: 'lfsr', port: 'out' }, to: { moduleId: 'xor', port: 'b' } },
        { from: { moduleId: 'xor', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      clock: { x: 48, y: 72 },
      plain: { x: 48, y: 262 },
      lfsr: { x: 292, y: 72 },
      xor: { x: 536, y: 168 },
      output: { x: 780, y: 168 },
    },
  },
  {
    id: 'gated-keystream',
    name: 'Gated Keystream',
    group: 'Conditional Clocking',
    summary: 'One clocked LFSR gates a second keystream register, creating a dependent clock chain in the bit domain.',
    pipeline: 'Clock -> Gate LFSR -> Data LFSR -> XOR(BitSource) -> BitOutput',
    defaultTickedMode: true,
    project: {
      modules: [
        { id: 'clock', defId: 'Clock', params: { period: 1, offset: 0, length: 8 } },
        { id: 'plain', defId: 'BitSource', params: { stream: [1, 0, 1, 1, 0, 0, 1, 0] } },
        {
          id: 'gate',
          defId: 'LFSR',
          params: { seed: [1, 0, 0, 1, 1], taps: '0,2', outputLength: 1 },
        },
        {
          id: 'data',
          defId: 'LFSR',
          params: { seed: [1, 1, 0, 1, 0], taps: '1,3', outputLength: 1 },
        },
        { id: 'xor', defId: 'XOR', params: {} },
        { id: 'output', defId: 'BitOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'gate', port: 'clock' } },
        { from: { moduleId: 'gate', port: 'out' }, to: { moduleId: 'data', port: 'clock' } },
        { from: { moduleId: 'plain', port: 'out' }, to: { moduleId: 'xor', port: 'a' } },
        { from: { moduleId: 'data', port: 'out' }, to: { moduleId: 'xor', port: 'b' } },
        { from: { moduleId: 'xor', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      clock: { x: 40, y: 64 },
      plain: { x: 40, y: 256 },
      gate: { x: 260, y: 64 },
      data: { x: 500, y: 64 },
      xor: { x: 720, y: 168 },
      output: { x: 940, y: 168 },
    },
  },
  {
    id: 'majority-keystream',
    name: 'Majority-Clocked Keystream',
    group: 'Conditional Clocking',
    summary: 'Three visible control registers vote through Majority on whether a data register advances, making irregular clocking explicit instead of hidden.',
    pipeline: 'Clock -> 3 Control LFSRs -> Majority -> Gate(clock pulse) -> Data LFSR -> XOR(BitSource) -> BitOutput',
    defaultTickedMode: true,
    project: {
      modules: [
        { id: 'clock', defId: 'Clock', params: { period: 1, offset: 0, length: 8 } },
        { id: 'plain', defId: 'BitSource', params: { stream: [1, 0, 1, 1, 0, 0, 1, 0] } },
        {
          id: 'control-a',
          defId: 'LFSR',
          params: { seed: [1, 0, 1, 0, 1], taps: '0,2', outputLength: 1 },
        },
        {
          id: 'control-b',
          defId: 'LFSR',
          params: { seed: [1, 1, 0, 1, 0], taps: '1,3', outputLength: 1 },
        },
        {
          id: 'control-c',
          defId: 'LFSR',
          params: { seed: [0, 1, 1, 0, 1], taps: '0,3', outputLength: 1 },
        },
        { id: 'majority', defId: 'Majority', params: {} },
        { id: 'gate', defId: 'Gate', params: {} },
        {
          id: 'data',
          defId: 'LFSR',
          params: { seed: [1, 1, 0, 0, 1], taps: '1,4', outputLength: 1 },
        },
        { id: 'xor', defId: 'XOR', params: {} },
        { id: 'output', defId: 'BitOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'control-a', port: 'clock' } },
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'control-b', port: 'clock' } },
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'control-c', port: 'clock' } },
        { from: { moduleId: 'control-a', port: 'out' }, to: { moduleId: 'majority', port: 'a' } },
        { from: { moduleId: 'control-b', port: 'out' }, to: { moduleId: 'majority', port: 'b' } },
        { from: { moduleId: 'control-c', port: 'out' }, to: { moduleId: 'majority', port: 'c' } },
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'gate', port: 'in' } },
        { from: { moduleId: 'majority', port: 'out' }, to: { moduleId: 'gate', port: 'control' } },
        { from: { moduleId: 'gate', port: 'out' }, to: { moduleId: 'data', port: 'clock' } },
        { from: { moduleId: 'plain', port: 'out' }, to: { moduleId: 'xor', port: 'a' } },
        { from: { moduleId: 'data', port: 'out' }, to: { moduleId: 'xor', port: 'b' } },
        { from: { moduleId: 'xor', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      clock: { x: 40, y: 56 },
      plain: { x: 40, y: 296 },
      'control-a': { x: 280, y: 24 },
      'control-b': { x: 280, y: 136 },
      'control-c': { x: 280, y: 248 },
      majority: { x: 540, y: 136 },
      gate: { x: 800, y: 136 },
      data: { x: 1060, y: 56 },
      xor: { x: 1320, y: 184 },
      output: { x: 1580, y: 184 },
    },
  },
  {
    id: 'filtered-keystream',
    name: 'Filtered Keystream',
    group: 'Conditional Clocking',
    summary: 'One visible control bit selects which of two candidate keystream bits continues forward before masking the plaintext.',
    pipeline: 'Clock -> Control LFSR + Data A LFSR + Data B LFSR -> Mux -> XOR(BitSource) -> BitOutput',
    project: {
      modules: [
        { id: 'clock', defId: 'Clock', params: { period: 1, offset: 0, length: 8 } },
        { id: 'plain', defId: 'BitSource', params: { stream: [1, 0, 1, 1, 0, 0, 1, 0] } },
        {
          id: 'control',
          defId: 'LFSR',
          params: { seed: [1], taps: '0', outputLength: 1 },
        },
        {
          id: 'data-a',
          defId: 'LFSR',
          params: { seed: [1], taps: '0', outputLength: 1 },
        },
        {
          id: 'data-b',
          defId: 'LFSR',
          params: { seed: [0], taps: '0', outputLength: 1 },
        },
        { id: 'mux', defId: 'Mux', params: {} },
        { id: 'xor', defId: 'XOR', params: {} },
        { id: 'output', defId: 'BitOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'control', port: 'clock' } },
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'data-a', port: 'clock' } },
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'data-b', port: 'clock' } },
        { from: { moduleId: 'control', port: 'out' }, to: { moduleId: 'mux', port: 'select' } },
        { from: { moduleId: 'data-a', port: 'out' }, to: { moduleId: 'mux', port: 'a' } },
        { from: { moduleId: 'data-b', port: 'out' }, to: { moduleId: 'mux', port: 'b' } },
        { from: { moduleId: 'plain', port: 'out' }, to: { moduleId: 'xor', port: 'a' } },
        { from: { moduleId: 'mux', port: 'out' }, to: { moduleId: 'xor', port: 'b' } },
        { from: { moduleId: 'xor', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      clock: { x: 40, y: 56 },
      plain: { x: 40, y: 296 },
      control: { x: 300, y: 24 },
      'data-a': { x: 300, y: 152 },
      'data-b': { x: 300, y: 280 },
      mux: { x: 560, y: 152 },
      xor: { x: 820, y: 224 },
      output: { x: 1080, y: 224 },
    },
  },
  {
    id: 'routed-clock-keystream',
    name: 'Routed Clock Keystream',
    group: 'Conditional Clocking',
    summary: 'One visible control bit routes the live clock pulse into one of two candidate data registers before their outputs are recombined.',
    pipeline: 'Clock -> Demux(select, pulse) -> Data A LFSR + Data B LFSR -> XOR -> XOR(BitSource) -> BitOutput',
    project: {
      modules: [
        { id: 'clock', defId: 'Clock', params: { period: 1, offset: 0, length: 8 } },
        { id: 'plain', defId: 'BitSource', params: { stream: [1, 0, 1, 1, 0, 0, 1, 0] } },
        {
          id: 'control',
          defId: 'LFSR',
          params: { seed: [1], taps: '0', outputLength: 1 },
        },
        { id: 'route', defId: 'Demux', params: {} },
        {
          id: 'data-a',
          defId: 'LFSR',
          params: { seed: [1], taps: '0', outputLength: 1 },
        },
        {
          id: 'data-b',
          defId: 'LFSR',
          params: { seed: [0], taps: '0', outputLength: 1 },
        },
        { id: 'mix', defId: 'XOR', params: {} },
        { id: 'xor', defId: 'XOR', params: {} },
        { id: 'output', defId: 'BitOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'control', port: 'clock' } },
        { from: { moduleId: 'control', port: 'out' }, to: { moduleId: 'route', port: 'select' } },
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'route', port: 'in' } },
        { from: { moduleId: 'route', port: 'a' }, to: { moduleId: 'data-a', port: 'clock' } },
        { from: { moduleId: 'route', port: 'b' }, to: { moduleId: 'data-b', port: 'clock' } },
        { from: { moduleId: 'data-a', port: 'out' }, to: { moduleId: 'mix', port: 'a' } },
        { from: { moduleId: 'data-b', port: 'out' }, to: { moduleId: 'mix', port: 'b' } },
        { from: { moduleId: 'plain', port: 'out' }, to: { moduleId: 'xor', port: 'a' } },
        { from: { moduleId: 'mix', port: 'out' }, to: { moduleId: 'xor', port: 'b' } },
        { from: { moduleId: 'xor', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      clock: { x: 40, y: 56 },
      plain: { x: 40, y: 312 },
      control: { x: 280, y: 24 },
      route: { x: 520, y: 56 },
      'data-a': { x: 780, y: 24 },
      'data-b': { x: 780, y: 184 },
      mix: { x: 1040, y: 104 },
      xor: { x: 1300, y: 232 },
      output: { x: 1560, y: 232 },
    },
  },
  {
    id: 'hybrid',
    name: 'Hybrid Reference',
    summary: 'The V1 hybrid machine crossing classical and modern domains.',
    pipeline: 'TextInput -> Rotor -> Reflector -> Rotor -> SymbolToBits -> XOR -> BitsToSymbol -> TextOutput',
    project: {
      modules: [
        { id: 'text', defId: 'TextInput', params: { value: 'A' } },
        {
          id: 'rotor-fwd',
          defId: 'Rotor',
          params: { wiring: 'EKMFLGDQVZNTOWYHXUSPAIBRCJ'.split(''), position: 0 },
        },
        {
          id: 'reflector',
          defId: 'Reflector',
          params: { wiring: 'YRUHQSLDPXNGOKMIEBFZCWVJAT'.split('') },
        },
        {
          id: 'rotor-rev',
          defId: 'Rotor',
          params: { wiring: 'EKMFLGDQVZNTOWYHXUSPAIBRCJ'.split(''), position: 0 },
        },
        { id: 'encode', defId: 'SymbolToBits', params: {} },
        { id: 'key', defId: 'BitSource', params: { stream: [1, 0, 1, 1, 0] } },
        { id: 'xor', defId: 'XOR', params: {} },
        { id: 'decode', defId: 'BitsToSymbol', params: {} },
        { id: 'output', defId: 'TextOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'text', port: 'out' }, to: { moduleId: 'rotor-fwd', port: 'in' } },
        { from: { moduleId: 'rotor-fwd', port: 'out' }, to: { moduleId: 'reflector', port: 'in' } },
        { from: { moduleId: 'reflector', port: 'out' }, to: { moduleId: 'rotor-rev', port: 'in' } },
        { from: { moduleId: 'rotor-rev', port: 'out' }, to: { moduleId: 'encode', port: 'in' } },
        { from: { moduleId: 'encode', port: 'out' }, to: { moduleId: 'xor', port: 'a' } },
        { from: { moduleId: 'key', port: 'out' }, to: { moduleId: 'xor', port: 'b' } },
        { from: { moduleId: 'xor', port: 'out' }, to: { moduleId: 'decode', port: 'in' } },
        { from: { moduleId: 'decode', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
      ],
    },
    layout: {
      text: { x: 24, y: 132 },
      'rotor-fwd': { x: 184, y: 132 },
      reflector: { x: 344, y: 132 },
      'rotor-rev': { x: 504, y: 132 },
      encode: { x: 664, y: 132 },
      key: { x: 664, y: 304 },
      xor: { x: 824, y: 218 },
      decode: { x: 984, y: 132 },
      output: { x: 1144, y: 132 },
    },
  },
  {
    id: 'advanced-rotor-stepping',
    name: 'Advanced Rotor Stepping',
    summary: 'A bounded three-rotor machine with explicit turnover wiring, ring setting, and visible double-step control.',
    pipeline: 'TextInput -> Rotor -> Rotor -> Rotor -> TextOutput, with Clock -> Gate/OR control wiring for turnover and double-step',
    project: {
      modules: [
        { id: 'text', defId: 'TextInput', params: { value: 'AAAA' } },
        { id: 'clock', defId: 'Clock', params: { period: 1, offset: 0, length: 4 } },
        {
          id: 'right',
          defId: 'Rotor',
          params: {
            wiring: 'BDFHJLCPRTXVZNYEIWGAKMUSQO'.split(''),
            position: 15,
            ringOffset: 0,
            notches: 'Q',
          },
        },
        {
          id: 'middle',
          defId: 'Rotor',
          params: {
            wiring: 'AJDKSIRUXBLHWTMCQGZNPYFVOE'.split(''),
            position: 4,
            ringOffset: 0,
            notches: 'E',
          },
        },
        {
          id: 'left',
          defId: 'Rotor',
          params: {
            wiring: 'EKMFLGDQVZNTOWYHXUSPAIBRCJ'.split(''),
            position: 0,
            ringOffset: 2,
            notches: 'Q',
          },
        },
        { id: 'middle-vote', defId: 'OR', params: {} },
        { id: 'middle-gate', defId: 'Gate', params: {} },
        { id: 'left-gate', defId: 'Gate', params: {} },
        { id: 'output', defId: 'TextOutput', params: {} },
      ],
      connections: [
        { from: { moduleId: 'text', port: 'out' }, to: { moduleId: 'right', port: 'in' } },
        { from: { moduleId: 'right', port: 'out' }, to: { moduleId: 'middle', port: 'in' } },
        { from: { moduleId: 'middle', port: 'out' }, to: { moduleId: 'left', port: 'in' } },
        { from: { moduleId: 'left', port: 'out' }, to: { moduleId: 'output', port: 'in' } },
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'right', port: 'clock' } },
        { from: { moduleId: 'right', port: 'turnover' }, to: { moduleId: 'middle-vote', port: 'a' } },
        { from: { moduleId: 'middle', port: 'turnover' }, to: { moduleId: 'middle-vote', port: 'b' } },
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'middle-gate', port: 'in' } },
        { from: { moduleId: 'middle-vote', port: 'out' }, to: { moduleId: 'middle-gate', port: 'control' } },
        { from: { moduleId: 'middle-gate', port: 'out' }, to: { moduleId: 'middle', port: 'clock' } },
        { from: { moduleId: 'clock', port: 'pulse' }, to: { moduleId: 'left-gate', port: 'in' } },
        { from: { moduleId: 'middle', port: 'turnover' }, to: { moduleId: 'left-gate', port: 'control' } },
        { from: { moduleId: 'left-gate', port: 'out' }, to: { moduleId: 'left', port: 'clock' } },
      ],
    },
    layout: {
      text: { x: 40, y: 208 },
      clock: { x: 40, y: 40 },
      right: { x: 280, y: 208 },
      'middle-vote': { x: 520, y: 40 },
      'middle-gate': { x: 760, y: 40 },
      middle: { x: 760, y: 208 },
      'left-gate': { x: 1000, y: 40 },
      left: { x: 1240, y: 208 },
      output: { x: 1480, y: 208 },
    },
  },
];

export function runDemoProject(project: Project, registry: ModuleRegistry = V1_REGISTRY): ExecutionResult {
  return executeProject(project, registry);
}
