import type { ManualSection } from './manual-content';

export const INSTRUCTOR_PILOT_SECTIONS: ManualSection[] = [
  {
    id: 'choose-your-path',
    title: 'Choose Your Path',
    summary: 'Pick a lab family and get a concrete first step before the session.',
    entries: [
      {
        id: 'which-lab-to-choose',
        title: 'Which Lab To Choose',
        body: 'Pick one flagship line before the pilot. Both are complete teaching arcs. The difference is which concept your course is already building toward.',
        pilotDecisions: [
          {
            label: 'Classical — LAB-1.x',
            description: 'Enigma-style rotor machine',
            bestFor: 'Mechanical intuition, historical grounding, and visible substitution + stepping logic',
            startWith: 'LAB-1.1 — Rotor Return Path',
          },
          {
            label: 'Modern — LAB-2.x',
            description: 'Byte S-Box + Feistel network',
            bestFor: 'Modern round structure, byte-level transforms, and diffusion analysis',
            startWith: 'LAB-2.1 — Byte S-Box Round',
          },
        ],
        indexTerms: ['which lab', 'classical line', 'modern line', 'lab 1', 'lab 2', 'choose a lab', 'first pilot'],
      },
      {
        id: 'why-mcw-is-worth-it',
        title: 'Why MCW Is Worth The Class Time',
        body: 'MCW earns its place when students need to explain a machine, not just observe one.',
        keyPoints: [
          'Students operate and repair a real cipher instead of reading about it.',
          'Every transformation is visible — nothing is hidden behind a black-box result.',
          'Students prove the machine works by repairing a broken version and verifying it against a known reference.',
          'If you include Python export, students leave with runnable code that agrees with the machine they built.',
        ],
        indexTerms: ['why mcw', 'what mcw teaches', 'glass box', 'distinctive value', 'worth class time', 'repair', 'verify'],
      },
    ],
  },
  {
    id: 'plan-the-session',
    title: 'Plan The Session',
    summary: 'Concrete session plans with timing and explicit decision points.',
    entries: [
      {
        id: 'one-class-plan',
        title: 'One-Class Plan (50–75 min)',
        body: 'A single session works when built around one arc: orient, read, repair, confirm. The goal is not to cover everything — it is to complete the repair loop.',
        keyPoints: [
          '**10 min** — Orient: open Quick Start and the flagship demo together. Students read the graph before touching anything.',
          '**20 min** — Guide: switch to Guide mode. Follow the tutorial prompts. Pause at the key mechanism — rotor turnover for LAB-1, SubBytes step for LAB-2.',
          '**15–20 min** — Repair: open the linked challenge. The goal is one successful repair, not perfection.',
          '**10 min** — Confirm: run Compare or Verification. Say out loud what PASS means before the session ends.',
        ],
        routeBlock: {
          useThisWhen: 'You have one class period and want a complete build-read-repair arc.',
          then: 'Add a second session for cryptanalysis and parity if time allows.',
          ifRepairPractice: 'If the repair finishes early, add a known-vector check in Verification before the confirmation step.',
        },
        seeAlso: ['two-session-plan', 'if-running-short'],
        indexTerms: ['one class', '50 minute', '75 minute', 'pilot session', 'class plan', 'lesson format', 'agenda'],
      },
      {
        id: 'two-session-plan',
        title: 'Two-Session Plan',
        body: 'Two sessions let you separate the machine arc from the trust arc. Both sessions feel complete on their own.',
        keyPoints: [
          '**Session 1**: Core machine path + repair challenge. End when students can name what they fixed and why.',
          '**Session 2**: Verification, Analyze, and parity export discussion. Open with a two-minute recap of the repair from session 1.',
          'Good split for Classical: rotor mechanics in session 1, verification + Python export in session 2.',
          'Good split for Modern: byte round + Feistel in session 1, Avalanche experiment (LAB-2.3) + parity in session 2.',
        ],
        routeBlock: {
          useThisWhen: 'You have two sessions and want both the mechanics and the trust layer.',
          then: 'The Avalanche experiment (LAB-2.3) is the strongest enrichment stop for a Modern session 2.',
        },
        seeAlso: ['one-class-plan', 'verification-and-export-in-pilot'],
        indexTerms: ['two sessions', 'short sequence', 'follow-up class', 'lab arc', 'two class', 'session 2'],
      },
      {
        id: 'if-running-short',
        title: 'If You Run Short On Time',
        body: 'Know in advance what to cut. The repair is the most valuable part of any pilot — cut outward from there.',
        keyPoints: [
          'Cut first: Python export. Show the ZIP contents and describe what verify_parity.py would prove. Takes 2 minutes instead of 10.',
          'Cut second: Cryptanalysis and Avalanche boards. They add depth but are not the core arc.',
          'Do not cut: orientation, at least one repair, and one verification comparison. These three are the pilot.',
        ],
        seeAlso: ['one-class-plan', 'python-setup-too-long'],
        indexTerms: ['running short', 'time pressure', 'cut', 'what to skip', 'not enough time', 'tight schedule'],
      },
    ],
  },
  {
    id: 'run-the-class',
    title: 'Run The Class',
    summary: 'What to tell students, what to watch for, and how to handle verification and export.',
    entries: [
      {
        id: 'student-workflow',
        title: 'What Students Should Do',
        body: 'Give students a four-step workflow before they touch anything. Keep it repeatable across the session.',
        keyPoints: [
          'Open the demo. Read the graph from source to sink before changing anything.',
          'Switch to Guide mode. Follow the tutorial prompts instead of free-exploring.',
          'Open the linked challenge. Repair the broken machine to match the visible target.',
          'Use Compare or Verification to confirm the repair. Name what the result means.',
          'If something is confusing, open Analyze or Trace on the specific module before asking for help.',
        ],
        seeAlso: ['moments-to-watch', 'one-class-plan'],
        indexTerms: ['student workflow', 'guide mode', 'repair challenge', 'analyze', 'trace', 'what students do', 'four steps'],
      },
      {
        id: 'moments-to-watch',
        title: 'Key Moments To Watch For',
        body: 'These specific moments tell you whether MCW is working as a teaching surface.',
        keyPoints: [
          '**Working**: Students describe a transformation in cause-and-effect terms. ("The rotor shifts because the notch is here.") This is the signal you are looking for.',
          '**Working**: Students open Analyze or Trace without being prompted. The graph is legible enough to invite inspection.',
          '**Working**: Students identify the wrong parameter in the repair challenge before changing anything. They have a hypothesis.',
          '**Struggling**: Students cannot find the right surface — Guide vs. Challenge vs. Build. This is the most common first-session navigation failure.',
          '**Struggling**: Students treat verification as a score rather than a trust check. They do not understand what PASS means.',
        ],
        seeAlso: ['what-to-watch-for', 'students-cant-explain'],
        indexTerms: ['key moments', 'observe students', 'what to watch', 'navigation failure', 'working signs', 'struggling signs'],
      },
      {
        id: 'verification-and-export-in-pilot',
        title: 'Verification And Export In A Pilot',
        body: 'Frame verification as the trust question, not as a grading step or an afterthought.',
        keyPoints: [
          'Before running verification, name the question: "We want to know if this machine matches the reference for these inputs."',
          'PASS means "matches the chosen reference behavior" — not "is cryptographically secure." Say this explicitly.',
          'For Python export: frame it as a handoff proof. The authored machine should behave identically when run as code.',
          'If local Python setup is uncertain: open the ZIP and show its contents. Read one exported function. Explain what verify_parity.py would prove.',
          'Do not let environment setup become the center of the lesson.',
        ],
        seeAlso: ['one-class-plan', 'python-setup-too-long'],
        indexTerms: ['verification', 'compare', 'parity', 'verify_parity.py', 'python export', 'trust check', 'what pass means', 'handoff proof'],
      },
    ],
  },
  {
    id: 'troubleshoot',
    title: 'Troubleshoot',
    summary: 'Quick fixes for the five most common first-pilot friction points.',
    entries: [
      {
        id: 'class-running-short',
        title: 'Class Is Running Short',
        body: 'The session is running short and you have not reached verification yet.',
        diagnosis: {
          likelyCause: 'Orientation ran longer than planned, or the repair challenge took more time than expected.',
          whatToCheck: 'Have students completed at least one repair? If yes, that is enough. Verification can be demonstrated from the front rather than run by each student.',
          whatToDoNext: 'Skip Python export entirely — describe what it would prove in one minute. Run one verification comparison from the front of the room and end with that PASS visible on screen.',
        },
        seeAlso: ['if-running-short', 'verification-and-export-in-pilot'],
        indexTerms: ['running short', 'not enough time', 'class time', 'time pressure', 'over time'],
      },
      {
        id: 'students-stuck-verification',
        title: 'Students Are Stuck At Verification',
        body: 'Students completed the repair but verification is failing or they cannot interpret the result.',
        diagnosis: {
          likelyCause: 'The repair has an error the student has not caught, or they have not imported the correct known vector.',
          whatToCheck: 'Open Compare and point to the first divergence. Ask the student: "What is different here, and why?"',
          whatToDoNext: 'Name the trust question explicitly before proceeding. Use the first failing case as teaching material — it shows exactly where the machine disagrees with the reference.',
        },
        seeAlso: ['verification-and-export-in-pilot', 'moments-to-watch'],
        indexTerms: ['verification stuck', 'verification failing', 'students stuck', 'compare', 'first divergence', 'repair wrong'],
      },
      {
        id: 'python-setup-too-long',
        title: 'Python Setup Is Taking Too Long',
        body: 'Environment setup is consuming lesson time.',
        diagnosis: {
          likelyCause: 'pip install, Python version conflicts, or path issues are taking longer than the lesson budget allows.',
          whatToCheck: 'Is the learning goal export parity, or understanding what parity means? These are different things. You can teach the concept without a running environment.',
          whatToDoNext: 'Open the ZIP bundle and show its contents without running it. Read one exported function and explain what it is doing. The point — code and machine must agree — lands without a running Python interpreter.',
        },
        seeAlso: ['verification-and-export-in-pilot', 'if-running-short'],
        indexTerms: ['python setup', 'environment setup', 'pip install', 'too long', 'parity without python', 'zip bundle'],
      },
      {
        id: 'students-cant-explain',
        title: 'Students Can\'t Explain The Machine',
        body: 'Students completed the tutorial steps but cannot describe what the machine is doing or why.',
        diagnosis: {
          likelyCause: 'Students followed instructions without connecting the visible graph to the transformation logic.',
          whatToCheck: 'Ask one student to trace a single signal path from source to sink and name what each module does. This reveals immediately whether they understand the graph or just executed steps.',
          whatToDoNext: 'Open Analyze on one module. Ask students to read the result aloud. Then ask: "What would change if this parameter were different?" One module at a time is enough to rebuild understanding.',
        },
        seeAlso: ['moments-to-watch', 'student-workflow'],
        indexTerms: ["can't explain", 'student understanding', 'explain the machine', 'graph reading', 'analyze', 'cause and effect'],
      },
      {
        id: 'challenge-difficulty',
        title: 'The Repair Challenge Was Too Easy Or Too Hard',
        body: 'The repair challenge did not match where students were in the sequence.',
        diagnosis: {
          likelyCause: 'Students opened Challenge mode before finishing the tutorial, or the parameter fault was obvious and required no real diagnosis.',
          whatToCheck: 'Did students complete the guided tutorial path before attempting the repair? The challenge is calibrated for students who have read the machine first.',
          whatToDoNext: 'If too hard — return to the demo in Build mode and identify the broken parameter together before reopening Challenge mode. If too easy — add a verification step: students must prove the repair with a known vector, not just match the visible target.',
        },
        seeAlso: ['student-workflow', 'moments-to-watch'],
        indexTerms: ['challenge too hard', 'challenge too easy', 'repair difficulty', 'challenge calibration', 'too easy', 'too hard'],
      },
    ],
  },
  {
    id: 'after-the-pilot',
    title: 'After The Pilot',
    summary: 'What to observe during the session and which questions to ask students afterward.',
    entries: [
      {
        id: 'what-to-watch-for',
        title: 'What To Watch For During Class',
        body: 'Useful pilot evidence is behavioral, not opinion-based. Watch for these patterns.',
        keyPoints: [
          '**Navigation**: Where do students get lost opening surfaces? Note the exact step — finding Guide vs. Challenge, or locating Atlas.',
          '**Explanation**: Can they say why the machine behaved as it did? Not what happened — why.',
          '**Repair approach**: Do they form a hypothesis before changing a parameter, or try values at random?',
          '**Verification**: Do they understand that PASS means "matches the reference," or treat it as a score?',
          '**Recovery**: Can a student recover from a broken lab without instructor rescue? This is the strongest signal.',
        ],
        seeAlso: ['questions-to-ask-afterward', 'moments-to-watch'],
        indexTerms: ['observe students', 'pilot evidence', 'behavioral evidence', 'what to watch', 'navigation failures', 'hypothesis'],
      },
      {
        id: 'questions-to-ask-afterward',
        title: 'Questions To Ask Afterward',
        body: 'Five questions worth asking. Short answers are more useful than long ones.',
        keyPoints: [
          'Which part of the machine became clearer because you could see it?',
          'Where did the workflow feel confusing or slow?',
          'Did verification help your understanding, or just add steps?',
          'Did the lab feel like one connected sequence or several separate tools?',
          'Would you attempt the same lab again with less instructor guidance?',
        ],
        seeAlso: ['what-to-watch-for'],
        indexTerms: ['post pilot', 'student feedback', 'instructor feedback', 'pilot review', 'questions', 'debrief', 'five questions'],
      },
    ],
  },
];
