import type { GuidedTutorial } from './tutorials';

export const STARTER_TUTORIALS: GuidedTutorial[] = [
  {
    version: 1,
    id: 'lorenz-foundation',
    title: 'The Lorenz Foundation',
    group: 'Historical Bridges',
    summary: 'Learn how a teleprinter-era keystream masks Baudot text with an LFSR before decoding it back into readable output.',
    projectId: 'lorenz-foundation',
    steps: [
      {
        id: 'lorenz-clock',
        title: 'Tick The Telegraph',
        body: 'Clock advances the keystream register one codeword at a time. This keeps the message rhythm explicit instead of hiding it inside a batch transform.',
        focusModuleId: 'clock',
        targetStepIndex: 0,
      },
      {
        id: 'lorenz-source',
        title: 'Feed One Baudot Codeword Per Tick',
        body: 'BaudotSource slices one teleprinter character into 5 bits on each tick. The ciphertext stays visible as real Baudot codewords rather than opaque text.',
        focusModuleId: 'source',
        targetStepIndex: 1,
      },
      {
        id: 'lorenz-lfsr',
        title: 'Generate The Key Stream',
        body: 'LFSR emits one 5-bit keystream slice on each live pulse. This stands in for the wheel-driven keystream logic of Lorenz-style machines.',
        focusModuleId: 'lfsr',
        targetStepIndex: 2,
      },
      {
        id: 'lorenz-xor',
        title: 'Mix Ciphertext And Key',
        body: 'XOR combines the incoming Baudot bits with the keystream bits. This is the core teleprinter masking step that links Lorenz-era systems to modern stream ciphers.',
        focusModuleId: 'xor',
        targetStepIndex: 3,
      },
      {
        id: 'lorenz-decode',
        title: 'Decode Back To Telegraph Text',
        body: 'BitsToBaudot groups the unmixed bits back into 5-bit codewords and decodes them into readable teleprinter text.',
        focusModuleId: 'decode',
        targetStepIndex: 4,
      },
      {
        id: 'lorenz-output',
        title: 'Read The Recovered Message',
        body: 'Output marks the final recovered teleprinter message. This closes the loop from historical bridge to keystream logic and back again.',
        focusModuleId: 'output',
        targetStepIndex: 5,
      },
    ],
  },
  {
    version: 1,
    id: 'baudot-bridge',
    title: 'The Baudot Telegraph',
    group: 'Historical Bridges',
    summary: 'Learn how teleprinter-era Baudot codewords cross into the bit domain and back again.',
    projectId: 'baudot-bridge',
    steps: [
      {
        id: 'baudot-source',
        title: 'Inject Baudot Text',
        body: 'BaudotSource emits letters-mode ITA2 codewords directly as 5-bit groups. This is the historical teleprinter bridge into the bit domain.',
        focusModuleId: 'source',
        targetStepIndex: 0,
      },
      {
        id: 'baudot-decode',
        title: 'Decode The 5-Bit Stream',
        body: 'BitsToBaudot groups the incoming bits into 5-bit codewords and decodes them back into teleprinter text. This keeps the bridge explicit instead of hiding the encoding.',
        focusModuleId: 'decode',
        targetStepIndex: 1,
      },
      {
        id: 'baudot-output',
        title: 'Read The Telegraph Result',
        body: 'Output marks the final decoded teleprinter text so students can inspect or compare the bridge result like any other machine.',
        focusModuleId: 'output',
        targetStepIndex: 2,
      },
    ],
  },
  {
    version: 1,
    id: 'bridge-walkthrough',
    title: 'Bridge Walkthrough',
    group: 'Foundations',
    summary: 'Learn how MCW crosses from letters into bits and back again.',
    projectId: 'bridge',
    steps: [
      {
        id: 'bridge-text',
        title: 'Start With A Symbol',
        body: 'The TextInput module emits one letter into the graph. This is the symbolic side of the workbench.',
        focusModuleId: 'text',
        targetStepIndex: 0,
      },
      {
        id: 'bridge-encode',
        title: 'Cross Into Bits',
        body: 'SymbolToBits is an explicit bridge. It turns the incoming letter into a 5-bit value so bit-domain modules can operate on it.',
        focusModuleId: 'encode',
        targetStepIndex: 1,
      },
      {
        id: 'bridge-xor',
        title: 'Mix With A Bit Key',
        body: 'XOR combines the encoded symbol bits with the BitSource key stream. This is the key mixing step in the bridge pipeline.',
        focusModuleId: 'xor',
        targetStepIndex: 2,
      },
      {
        id: 'bridge-decode',
        title: 'Return To Symbols',
        body: 'BitsToSymbol converts the transformed 5-bit value back into a readable letter result.',
        focusModuleId: 'decode',
        targetStepIndex: 3,
      },
      {
        id: 'bridge-output',
        title: 'Read The Result',
        body: 'Output marks the final signal students should inspect while stepping or comparing runs.',
        focusModuleId: 'output',
        targetStepIndex: 4,
      },
    ],
  },
  {
    version: 1,
    id: 'byte-round',
    title: 'The Byte Round',
    group: 'Modern Rounds',
    summary: 'Learn how an 8-bit S-Box and permutation transform a byte without leaving the bit domain.',
    projectId: 'byte-round',
    steps: [
      {
        id: 'byte-source',
        title: 'Start With One Byte',
        body: 'BitSource emits a full 8-bit value into the round. In this demo the machine stays entirely in the bit domain from start to finish.',
        focusModuleId: 'source',
        targetStepIndex: 0,
      },
      {
        id: 'byte-sbox',
        title: 'Substitute The Byte',
        body: 'SBox groups the incoming bits into one 8-bit chunk because its table has 256 entries. This is the same substitution pattern used by real byte-oriented ciphers.',
        focusModuleId: 'sbox',
        targetStepIndex: 1,
      },
      {
        id: 'byte-permute',
        title: 'Reorder The Bits',
        body: 'Permutation then rewires the substituted byte by index. In this round the order is reversed so students can inspect how position changes without changing the bit values themselves.',
        focusModuleId: 'permute',
        targetStepIndex: 2,
      },
      {
        id: 'byte-output',
        title: 'End In Bits',
        body: 'BitOutput marks the terminal sink for a bit-domain machine. Use the Analyze view and challenge workflow here without forcing the round back into symbols.',
        focusModuleId: 'output',
        targetStepIndex: 3,
      },
    ],
  },
  {
    version: 1,
    id: 'hex-round',
    title: 'The Hex Round',
    group: 'Bridge Rounds',
    summary: 'Learn how MCW can start from a hex test vector, transform it in bits, and return to hex.',
    projectId: 'hex-round',
    steps: [
      {
        id: 'hex-source',
        title: 'Inject A Hex Vector',
        body: 'HexSource lets students paste byte-oriented values directly into the graph. This is the easiest way to bring real cipher test vectors into the modern foundry.',
        focusModuleId: 'source',
        targetStepIndex: 0,
      },
      {
        id: 'hex-sbox',
        title: 'Substitute In Bits',
        body: 'Once the hex value becomes bits, the round works exactly like the byte-domain S-Box machine. The nonlinear substitution still happens entirely in the bit domain.',
        focusModuleId: 'sbox',
        targetStepIndex: 1,
      },
      {
        id: 'hex-permute',
        title: 'Permute The Byte',
        body: 'Permutation reorders the substituted bits before they are rendered again. This is where diffusion-style structure shows up in a byte-oriented round.',
        focusModuleId: 'permute',
        targetStepIndex: 2,
      },
      {
        id: 'hex-bridge-back',
        title: 'Bridge Back To Hex',
        body: 'BitsToHex converts the transformed bit signal back into hexadecimal text so students can compare outputs against familiar byte-scale references.',
        focusModuleId: 'encode',
        targetStepIndex: 3,
      },
      {
        id: 'hex-output',
        title: 'Read The Byte Result',
        body: 'Output marks the final hex result. This gives the workbench a complete hex-in, hex-out path for modern round experiments.',
        focusModuleId: 'output',
        targetStepIndex: 4,
      },
    ],
  },
  {
    version: 1,
    id: 'ascii-round',
    title: 'The ASCII Round',
    group: 'Bridge Rounds',
    summary: 'Learn how MCW can start from ASCII text, transform bytes in bits, and return to readable text.',
    projectId: 'ascii-round',
    steps: [
      {
        id: 'ascii-source',
        title: 'Inject ASCII Text',
        body: 'AsciiSource converts readable ASCII text into 8-bit byte values. This gives the modern foundry a direct bridge from plain text into byte-oriented experiments.',
        focusModuleId: 'source',
        targetStepIndex: 0,
      },
      {
        id: 'ascii-sbox',
        title: 'Substitute The Byte',
        body: 'The S-Box still works on the byte as raw bits. This shows that byte-oriented ciphers can begin from text while remaining explicit about every transformation.',
        focusModuleId: 'sbox',
        targetStepIndex: 1,
      },
      {
        id: 'ascii-permute',
        title: 'Permute The Bits',
        body: 'Permutation reorders the substituted byte before it is rendered again. This is the same diffusion step used in the other modern rounds.',
        focusModuleId: 'permute',
        targetStepIndex: 2,
      },
      {
        id: 'ascii-bridge-back',
        title: 'Bridge Back To Text',
        body: 'BitsToAscii converts the transformed byte back into readable ASCII when the result stays within the 7-bit range. This makes byte-oriented experiments feel closer to ordinary text workflows.',
        focusModuleId: 'encode',
        targetStepIndex: 3,
      },
      {
        id: 'ascii-output',
        title: 'Read The Character Result',
        body: 'Output marks the final ASCII result so students can compare the transformed byte against the original text character directly.',
        focusModuleId: 'output',
        targetStepIndex: 4,
      },
    ],
  },
  {
    version: 1,
    id: 'sequential-heart',
    title: 'The Sequential Heart',
    group: 'Sequential',
    summary: 'Learn how a Clock drives an LFSR one tick at a time to produce a running symbol stream.',
    projectId: 'sequential',
    steps: [
      {
        id: 'sequential-clock',
        title: 'Time Enters The Graph',
        body: 'Clock is an explicit source of pulses. In ticked mode, each pulse marks one visible moment in the machine timeline.',
        focusModuleId: 'clock',
        targetStepIndex: 0,
      },
      {
        id: 'sequential-lfsr',
        title: 'Pulse The Register',
        body: 'The LFSR only advances when its clock input receives a 1 pulse. Watch its internal seed state change from tick to tick.',
        focusModuleId: 'lfsr',
        targetStepIndex: 1,
      },
      {
        id: 'sequential-decode',
        title: 'Decode Each 5-Bit Slice',
        body: 'BitsToSymbol turns the LFSR output for the current tick into a readable letter. This makes the keystream visible to students.',
        focusModuleId: 'decode',
        targetStepIndex: 2,
      },
      {
        id: 'sequential-output',
        title: 'Read The Stream Over Time',
        body: 'Output shows the current tick result, while the tick bar collects the full stream as you scrub or press play.',
        focusModuleId: 'output',
        targetStepIndex: 3,
      },
    ],
  },
  {
    version: 1,
    id: 'modern-keystream',
    title: 'The Modern Keystream',
    group: 'Sequential',
    summary: 'Learn how a clocked LFSR produces a running bit mask that XOR encrypts a plaintext stream.',
    projectId: 'keystream',
    steps: [
      {
        id: 'keystream-clock',
        title: 'Tick The Machine',
        body: 'Clock controls when the keystream register advances. In ticked mode each pulse corresponds to one bit of the running cipher stream.',
        focusModuleId: 'clock',
        targetStepIndex: 0,
      },
      {
        id: 'keystream-plain',
        title: 'Feed Plaintext Bits',
        body: 'BitSource provides the plaintext stream one bit at a time. This lets students inspect encryption at the exact bit being processed on the current tick.',
        focusModuleId: 'plain',
        targetStepIndex: 1,
      },
      {
        id: 'keystream-lfsr',
        title: 'Generate The Mask',
        body: 'LFSR emits one keystream bit per tick because its output length is 1. Its internal seed shifts after each live clock pulse, producing a running pseudo-random mask.',
        focusModuleId: 'lfsr',
        targetStepIndex: 2,
      },
      {
        id: 'keystream-xor',
        title: 'Mix Plaintext And Keystream',
        body: 'XOR combines the current plaintext bit with the current keystream bit. This is the core stream-cipher operation: plaintext XOR mask = ciphertext.',
        focusModuleId: 'xor',
        targetStepIndex: 3,
      },
      {
        id: 'keystream-output',
        title: 'Read The Cipher Stream',
        body: 'BitOutput marks the terminal ciphertext sink. Use the tick bar, probes, and challenge workflow here to inspect how the encrypted bit stream evolves over time.',
        focusModuleId: 'output',
        targetStepIndex: 4,
      },
    ],
  },
  {
    version: 1,
    id: 'gated-keystream',
    title: 'The Gated Keystream',
    group: 'Conditional Clocking',
    summary: 'Learn how one keystream register can control when a second register advances.',
    projectId: 'gated-keystream',
    steps: [
      {
        id: 'gated-clock',
        title: 'Drive The Gate Register',
        body: 'Clock advances the first LFSR on every tick. That register does not encrypt the plaintext directly; it decides when the next register is allowed to move.',
        focusModuleId: 'clock',
        targetStepIndex: 0,
      },
      {
        id: 'gated-gate',
        title: 'Generate The Step Signal',
        body: 'The gate LFSR emits one bit per tick. When that bit is 1, the second LFSR advances. When it is 0, the second register freezes for that tick.',
        focusModuleId: 'gate',
        targetStepIndex: 1,
      },
      {
        id: 'gated-data',
        title: 'Advance Conditionally',
        body: 'The data LFSR now depends on another module for its clock. This is the core conditional-clocking idea: time is still explicit, but stepping can depend on machine state.',
        focusModuleId: 'data',
        targetStepIndex: 2,
      },
      {
        id: 'gated-xor',
        title: 'Mix With Plaintext',
        body: 'XOR combines the current plaintext bit with the gated keystream bit. Watch how repeated plaintext bits can encrypt differently when the data register pauses or advances.',
        focusModuleId: 'xor',
        targetStepIndex: 3,
      },
      {
        id: 'gated-output',
        title: 'Inspect The Resulting Stream',
        body: 'BitOutput marks the final ciphertext sink. Use the tick bar and history chips to see how the gate register changes the rhythm of the output stream.',
        focusModuleId: 'output',
        targetStepIndex: 4,
      },
    ],
  },
];
